services:
  - type: web
    name: god-madara-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
        
